### PR TITLE
minimum effort symfony6 compat

### PR DESCRIPTION
**Pull request by alexdo**

### CODE REVIEW

**Review by byWulf — APPROVED** [review]

**Comment by OskarStark** [comment]
It would be very helpful if you can merge this and create a release

**Comment by byWulf** [comment]
Merged and released as 3.4.0 @OskarStark :)

**Comment by OskarStark** [comment]
Very nice! Thanks

**Comment by OskarStark** [comment]
Hmm I get an error when requiring this version, do you face the same?
```
Problem 1
    - csa/guzzle-cache-middleware v1.0.0 requires symfony/filesystem ^2.7|^3.0|^4.0 -> found symfony/filesystem[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.42] but it conflicts with your root composer.json require (^6.1).
    - csa/guzzle-cache-middleware v1.0.1 requires symfony/filesystem ^2.7|^3.0|^4.0|^5.0 -> found symfony/filesystem[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.42, v5.0.0, ..., v5.4.9] but it conflicts with your root composer.json require (^6.1).
    - bywulf/guzzle-bundle 3.4.0 requires csa/guzzle-cache-middleware ^1.0.0 -> satisfiable by csa/guzzle-cache-middleware[v1.0.0, v1.0.1].
    - Root composer.json requires bywulf/guzzle-bundle ^3.4 -> satisfiable by bywulf/guzzle-bundle[3.4.0].
```

**Comment by byWulf** [comment]
Seems like the csa/guzzle-cache-middleware does not support symfony 6. 

Perhaps another fork of that bundle already supports it? Perhaps https://github.com/valkars/guzzle-cache-middleware ? But it doesn't seem to have a release yet.

**Pull request merged**
